export default movies = [
  {
    name: "Thiruchitrambalam",
    duration: "2hr 15m",
    genre: "Drama",
    discription: "The journey of Liger, from Karimnagar to Mumbai, from a nobody to a competitor, in his search for recognition while navigating his weaknesses, relationships, and love life.",
    price: "150",
    startDate: "01-09-22",
    endDate: "09-09-22",
    slots: ["150", "230", "340"],
    imageUrl: null,
    videoUrl: null,
  },
  {
    name: "Thiruchitrambalam",
    duration: "2hr 15m",
    genre: "Drama",
    discription:
      "The journey of Liger, from Karimnagar to Mumbai, from a nobody to a competitor, in his search for recognition while navigating his weaknesses, relationships, and love life.",
    price: "150",
    startDate: "01-09-22",
    endDate: "09-09-22",
    slots: ["150", "230", "340"],
    imageUrl: null,
    videoUrl: null,
  },
  {
    name: "Thiruchitrambalam",
    duration: "2hr 15m",
    genre: "Drama",
    discription:
      "The journey of Liger, from Karimnagar to Mumbai, from a nobody to a competitor, in his search for recognition while navigating his weaknesses, relationships, and love life.",
    price: "150",
    startDate: "01-09-22",
    endDate: "09-09-22",
    slots: ["150", "230", "340"],
    imageUrl: null,
    videoUrl: null,
  },
  {
    name: "Thiruchitrambalam",
    duration: "2hr 15m",
    genre: "Drama",
    discription:
      "The journey of Liger, from Karimnagar to Mumbai, from a nobody to a competitor, in his search for recognition while navigating his weaknesses, relationships, and love life.",
    price: "150",
    startDate: "01-09-22",
    endDate: "09-09-22",
    slots: ["150", "230", "340"],
    imageUrl: null,
    videoUrl: null,
  },
  {
    name: "Thiruchitrambalam",
    duration: "2hr 15m",
    genre: "Drama",
    discription:
      "The journey of Liger, from Karimnagar to Mumbai, from a nobody to a competitor, in his search for recognition while navigating his weaknesses, relationships, and love life.",
    price: "150",
    startDate: "01-09-22",
    endDate: "09-09-22",
    slots: ["150", "230", "340"],
    imageUrl: null,
    videoUrl: null,
  },
  {
    name: "Thiruchitrambalam",
    duration: "2hr 15m",
    genre: "Drama",
    discription:
      "The journey of Liger, from Karimnagar to Mumbai, from a nobody to a competitor, in his search for recognition while navigating his weaknesses, relationships, and love life.",
    price: "150",
    startDate: "01-09-22",
    endDate: "09-09-22",
    slots: ["150", "230", "340"],
    imageUrl: null,
    videoUrl: null,
  },
  {
    name: "Thiruchitrambalam",
    duration: "2hr 15m",
    genre: "Drama",
    discription:
      "The journey of Liger, from Karimnagar to Mumbai, from a nobody to a competitor, in his search for recognition while navigating his weaknesses, relationships, and love life.",
    price: "150",
    startDate: "01-09-22",
    endDate: "09-09-22",
    slots: ["150", "230", "340"],
    imageUrl: null,
    videoUrl: null,
  },
  {
    name: "Thiruchitrambalam",
    duration: "2hr 15m",
    genre: "Drama",
    discription:
      "The journey of Liger, from Karimnagar to Mumbai, from a nobody to a competitor, in his search for recognition while navigating his weaknesses, relationships, and love life.",
    price: "150",
    startDate: "01-09-22",
    endDate: "09-09-22",
    slots: ["150", "230", "340"],
    imageUrl: null,
    videoUrl: null,
  },
  {
    name: "Thiruchitrambalam",
    duration: "2hr 15m",
    genre: "Drama",
    discription:
      "The journey of Liger, from Karimnagar to Mumbai, from a nobody to a competitor, in his search for recognition while navigating his weaknesses, relationships, and love life.",
    price: "150",
    startDate: "01-09-22",
    endDate: "09-09-22",
    slots: ["150", "230", "340"],
    imageUrl: null,
    videoUrl: null,
  },
  {
    name: "Thiruchitrambalam",
    duration: "2hr 15m",
    genre: "Drama",
    discription:
      "The journey of Liger, from Karimnagar to Mumbai, from a nobody to a competitor, in his search for recognition while navigating his weaknesses, relationships, and love life.",
    price: "150",
    startDate: "01-09-22",
    endDate: "09-09-22",
    slots: ["150", "230", "340"],
    imageUrl: null,
    videoUrl: null,
  },
  {
    name: "Thiruchitrambalam",
    duration: "2hr 15m",
    genre: "Drama",
    discription:
      "The journey of Liger, from Karimnagar to Mumbai, from a nobody to a competitor, in his search for recognition while navigating his weaknesses, relationships, and love life.",
    price: "150",
    startDate: "01-09-22",
    endDate: "09-09-22",
    slots: ["150", "230", "340"],
    imageUrl: null,
    videoUrl: null,
  },
  {
    name: "Thiruchitrambalam",
    duration: "2hr 15m",
    genre: "Drama",
    discription:
      "The journey of Liger, from Karimnagar to Mumbai, from a nobody to a competitor, in his search for recognition while navigating his weaknesses, relationships, and love life.",
    price: "150",
    startDate: "01-09-22",
    endDate: "09-09-22",
    slots: ["150", "230", "340"],
    imageUrl: null,
    videoUrl: null,
  },
  {
    name: "Thiruchitrambalam",
    duration: "2hr 15m",
    genre: "Drama",
    discription:
      "The journey of Liger, from Karimnagar to Mumbai, from a nobody to a competitor, in his search for recognition while navigating his weaknesses, relationships, and love life.",
    price: "150",
    startDate: "01-09-22",
    endDate: "09-09-22",
    slots: ["150", "230", "340"],
    imageUrl: null,
    videoUrl: null,
  },
  {
    name: "Thiruchitrambalam",
    duration: "2hr 15m",
    genre: "Drama",
    discription:
      "The journey of Liger, from Karimnagar to Mumbai, from a nobody to a competitor, in his search for recognition while navigating his weaknesses, relationships, and love life.",
    price: "150",
    startDate: "01-09-22",
    endDate: "09-09-22",
    slots: ["150", "230", "340"],
    imageUrl: null,
    videoUrl: null,
  },
  {
    name: "Thiruchitrambalam",
    duration: "2hr 15m",
    genre: "Drama",
    discription:
      "The journey of Liger, from Karimnagar to Mumbai, from a nobody to a competitor, in his search for recognition while navigating his weaknesses, relationships, and love life.",
    price: "150",
    startDate: "01-09-22",
    endDate: "09-09-22",
    slots: ["150", "230", "340"],
    imageUrl: null,
    videoUrl: null,
  },
  {
    name: "Thiruchitrambalam",
    duration: "2hr 15m",
    genre: "Drama",
    discription:
      "The journey of Liger, from Karimnagar to Mumbai, from a nobody to a competitor, in his search for recognition while navigating his weaknesses, relationships, and love life.",
    price: "150",
    startDate: "01-09-22",
    endDate: "09-09-22",
    slots: ["150", "230", "340"],
    imageUrl: null,
    videoUrl: null,
  },
  {
    name: "Thiruchitrambalam",
    duration: "2hr 15m",
    genre: "Drama",
    discription:
      "The journey of Liger, from Karimnagar to Mumbai, from a nobody to a competitor, in his search for recognition while navigating his weaknesses, relationships, and love life.",
    price: "150",
    startDate: "01-09-22",
    endDate: "09-09-22",
    slots: ["150", "230", "340"],
    imageUrl: null,
    videoUrl: null,
  },
];
